// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	gatewayapiv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	versioned "github.com/envoyproxy/gateway/pkg/clientset/versioned"
	internalinterfaces "github.com/envoyproxy/gateway/pkg/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/envoyproxy/gateway/pkg/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EnvoyProxyInformer provides access to a shared informer and lister for
// EnvoyProxies.
type EnvoyProxyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.EnvoyProxyLister
}

type envoyProxyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEnvoyProxyInformer constructs a new informer for EnvoyProxy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEnvoyProxyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEnvoyProxyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEnvoyProxyInformer constructs a new informer for EnvoyProxy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEnvoyProxyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EnvoyGatewayV1alpha1().EnvoyProxies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EnvoyGatewayV1alpha1().EnvoyProxies(namespace).Watch(context.TODO(), options)
			},
		},
		&gatewayapiv1alpha1.EnvoyProxy{},
		resyncPeriod,
		indexers,
	)
}

func (f *envoyProxyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEnvoyProxyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *envoyProxyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&gatewayapiv1alpha1.EnvoyProxy{}, f.defaultInformer)
}

func (f *envoyProxyInformer) Lister() apiv1alpha1.EnvoyProxyLister {
	return apiv1alpha1.NewEnvoyProxyLister(f.Informer().GetIndexer())
}
