apiVersion: v1
kind: Service
metadata:
  name: gateway-ext-server-a
  namespace: envoy-gateway-system
spec:
  type: ClusterIP
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: grpc-gw-ext
  selector:
    app.kubernetes.io/name: gateway-ext-server-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-ext-server-a
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: gateway-ext-server-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-ext-server-a
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-ext-server-a
    spec:
      containers:
        - name: gateway-ext-server-a
          image: envoyproxy/gateway-simple-extension-server:latest
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --suffix=ext-a
          ports:
            - name: grpc-gw-ext
              containerPort: 5005
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-ext-server-b
  namespace: envoy-gateway-system
spec:
  type: ClusterIP
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: grpc-gw-ext
  selector:
    app.kubernetes.io/name: gateway-ext-server-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-ext-server-b
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: gateway-ext-server-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-ext-server-b
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-ext-server-b
    spec:
      containers:
        - name: gateway-ext-server-b
          image: envoyproxy/gateway-simple-extension-server:latest
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --suffix=ext-b
          ports:
            - name: grpc-gw-ext
              containerPort: 5005
              protocol: TCP
