//go:build !ignore_autogenerated

// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.



// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerContextExample) DeepCopyInto(out *ListenerContextExample) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerContextExample.
func (in *ListenerContextExample) DeepCopy() *ListenerContextExample {
	if in == nil { return nil }
	out := new(ListenerContextExample)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ListenerContextExample) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerContextExampleList) DeepCopyInto(out *ListenerContextExampleList) {
*out = *in
out.TypeMeta = in.TypeMeta
in.ListMeta.DeepCopyInto(&out.ListMeta)
if in.Items != nil {
in, out := &in.Items, &out.Items
*out = make([]ListenerContextExample, len(*in))
for i := range *in {
(*in)[i].DeepCopyInto(&(*out)[i])
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerContextExampleList.
func (in *ListenerContextExampleList) DeepCopy() *ListenerContextExampleList {
	if in == nil { return nil }
	out := new(ListenerContextExampleList)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ListenerContextExampleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerContextExampleSpec) DeepCopyInto(out *ListenerContextExampleSpec) {
*out = *in
if in.TargetRefs != nil {
in, out := &in.TargetRefs, &out.TargetRefs
*out = make([]invalid type, len(*in))
for i := range *in {
}
}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerContextExampleSpec.
func (in *ListenerContextExampleSpec) DeepCopy() *ListenerContextExampleSpec {
	if in == nil { return nil }
	out := new(ListenerContextExampleSpec)
	in.DeepCopyInto(out)
	return out
}

