name: setup-deps
description: Install host system dependencies

runs:
  using: composite
  steps:
    - shell: bash
      run: sudo apt-get install libbtrfs-dev -y
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v6.0.2
      with:
        go-version-file: go.mod
        cache: true
