name: setup-deps
description: Install host system dependencies

runs:
  using: composite
  steps:
    - shell: bash
      run: sudo apt-get install libbtrfs-dev -y
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.0.2
      with:
        go-version-file: go.mod
        cache: true
