apiVersion: v1
kind: ServiceAccount
# This's disabled by default to keep consistent with envoy-ratelimit 
# and provisioned envoy fleet, if the pod need to access k8s API, 
# could be enabled per pod.
automountServiceAccountToken: false
metadata:
  name: envoy-gateway
  namespace: {{ include "eg.namespace" . }}
  labels:
  {{- include "eg.labels" . | nindent 4 }}
