// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	scheme "github.com/envoyproxy/gateway/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BackendsGetter has a method to return a BackendInterface.
// A group's client should implement this interface.
type BackendsGetter interface {
	Backends(namespace string) BackendInterface
}

// BackendInterface has methods to work with Backend resources.
type BackendInterface interface {
	Create(ctx context.Context, backend *apiv1alpha1.Backend, opts v1.CreateOptions) (*apiv1alpha1.Backend, error)
	Update(ctx context.Context, backend *apiv1alpha1.Backend, opts v1.UpdateOptions) (*apiv1alpha1.Backend, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, backend *apiv1alpha1.Backend, opts v1.UpdateOptions) (*apiv1alpha1.Backend, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.Backend, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.BackendList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.Backend, err error)
	BackendExpansion
}

// backends implements BackendInterface
type backends struct {
	*gentype.ClientWithList[*apiv1alpha1.Backend, *apiv1alpha1.BackendList]
}

// newBackends returns a Backends
func newBackends(c *EnvoyGatewayV1alpha1Client, namespace string) *backends {
	return &backends{
		gentype.NewClientWithList[*apiv1alpha1.Backend, *apiv1alpha1.BackendList](
			"backends",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.Backend { return &apiv1alpha1.Backend{} },
			func() *apiv1alpha1.BackendList { return &apiv1alpha1.BackendList{} },
		),
	}
}
