// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	scheme "github.com/envoyproxy/gateway/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EnvoyProxiesGetter has a method to return a EnvoyProxyInterface.
// A group's client should implement this interface.
type EnvoyProxiesGetter interface {
	EnvoyProxies(namespace string) EnvoyProxyInterface
}

// EnvoyProxyInterface has methods to work with EnvoyProxy resources.
type EnvoyProxyInterface interface {
	Create(ctx context.Context, envoyProxy *apiv1alpha1.EnvoyProxy, opts v1.CreateOptions) (*apiv1alpha1.EnvoyProxy, error)
	Update(ctx context.Context, envoyProxy *apiv1alpha1.EnvoyProxy, opts v1.UpdateOptions) (*apiv1alpha1.EnvoyProxy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, envoyProxy *apiv1alpha1.EnvoyProxy, opts v1.UpdateOptions) (*apiv1alpha1.EnvoyProxy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.EnvoyProxy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.EnvoyProxyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.EnvoyProxy, err error)
	EnvoyProxyExpansion
}

// envoyProxies implements EnvoyProxyInterface
type envoyProxies struct {
	*gentype.ClientWithList[*apiv1alpha1.EnvoyProxy, *apiv1alpha1.EnvoyProxyList]
}

// newEnvoyProxies returns a EnvoyProxies
func newEnvoyProxies(c *EnvoyGatewayV1alpha1Client, namespace string) *envoyProxies {
	return &envoyProxies{
		gentype.NewClientWithList[*apiv1alpha1.EnvoyProxy, *apiv1alpha1.EnvoyProxyList](
			"envoyproxies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.EnvoyProxy { return &apiv1alpha1.EnvoyProxy{} },
			func() *apiv1alpha1.EnvoyProxyList { return &apiv1alpha1.EnvoyProxyList{} },
		),
	}
}
