// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/gateway/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeClientTrafficPolicies implements ClientTrafficPolicyInterface
type fakeClientTrafficPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.ClientTrafficPolicy, *v1alpha1.ClientTrafficPolicyList]
	Fake *FakeEnvoyGatewayV1alpha1
}

func newFakeClientTrafficPolicies(fake *FakeEnvoyGatewayV1alpha1, namespace string) apiv1alpha1.ClientTrafficPolicyInterface {
	return &fakeClientTrafficPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.ClientTrafficPolicy, *v1alpha1.ClientTrafficPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("clienttrafficpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("ClientTrafficPolicy"),
			func() *v1alpha1.ClientTrafficPolicy { return &v1alpha1.ClientTrafficPolicy{} },
			func() *v1alpha1.ClientTrafficPolicyList { return &v1alpha1.ClientTrafficPolicyList{} },
			func(dst, src *v1alpha1.ClientTrafficPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ClientTrafficPolicyList) []*v1alpha1.ClientTrafficPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ClientTrafficPolicyList, items []*v1alpha1.ClientTrafficPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
