// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/remoteinfra/service.proto

package remoteinfra

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateProxyInfra_FullMethodName     = "/envoygateway.remoteinfra.EnvoyGatewayRemoteInfrastructureProvider/CreateOrUpdateProxyInfra"
	EnvoyGatewayRemoteInfrastructureProvider_DeleteProxyInfra_FullMethodName             = "/envoygateway.remoteinfra.EnvoyGatewayRemoteInfrastructureProvider/DeleteProxyInfra"
	EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateRateLimitInfra_FullMethodName = "/envoygateway.remoteinfra.EnvoyGatewayRemoteInfrastructureProvider/CreateOrUpdateRateLimitInfra"
	EnvoyGatewayRemoteInfrastructureProvider_DeleteRateLimitInfra_FullMethodName         = "/envoygateway.remoteinfra.EnvoyGatewayRemoteInfrastructureProvider/DeleteRateLimitInfra"
)

// EnvoyGatewayRemoteInfrastructureProviderClient is the client API for EnvoyGatewayRemoteInfrastructureProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnvoyGatewayRemoteInfrastructureProviderClient interface {
	CreateOrUpdateProxyInfra(ctx context.Context, in *CreateOrUpdateProxyInfraRequest, opts ...grpc.CallOption) (*CreateOrUpdateProxyInfraResponse, error)
	DeleteProxyInfra(ctx context.Context, in *DeleteProxyInfraRequest, opts ...grpc.CallOption) (*DeleteProxyInfraResponse, error)
	CreateOrUpdateRateLimitInfra(ctx context.Context, in *CreateOrUpdateRateLimitInfraRequest, opts ...grpc.CallOption) (*CreateOrUpdateRateLimitInfraResponse, error)
	DeleteRateLimitInfra(ctx context.Context, in *DeleteRateLimitInfraRequest, opts ...grpc.CallOption) (*DeleteRateLimitInfraResponse, error)
}

type envoyGatewayRemoteInfrastructureProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvoyGatewayRemoteInfrastructureProviderClient(cc grpc.ClientConnInterface) EnvoyGatewayRemoteInfrastructureProviderClient {
	return &envoyGatewayRemoteInfrastructureProviderClient{cc}
}

func (c *envoyGatewayRemoteInfrastructureProviderClient) CreateOrUpdateProxyInfra(ctx context.Context, in *CreateOrUpdateProxyInfraRequest, opts ...grpc.CallOption) (*CreateOrUpdateProxyInfraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateProxyInfraResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateProxyInfra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyGatewayRemoteInfrastructureProviderClient) DeleteProxyInfra(ctx context.Context, in *DeleteProxyInfraRequest, opts ...grpc.CallOption) (*DeleteProxyInfraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProxyInfraResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayRemoteInfrastructureProvider_DeleteProxyInfra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyGatewayRemoteInfrastructureProviderClient) CreateOrUpdateRateLimitInfra(ctx context.Context, in *CreateOrUpdateRateLimitInfraRequest, opts ...grpc.CallOption) (*CreateOrUpdateRateLimitInfraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateRateLimitInfraResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateRateLimitInfra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyGatewayRemoteInfrastructureProviderClient) DeleteRateLimitInfra(ctx context.Context, in *DeleteRateLimitInfraRequest, opts ...grpc.CallOption) (*DeleteRateLimitInfraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRateLimitInfraResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayRemoteInfrastructureProvider_DeleteRateLimitInfra_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvoyGatewayRemoteInfrastructureProviderServer is the server API for EnvoyGatewayRemoteInfrastructureProvider service.
// All implementations must embed UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer
// for forward compatibility.
type EnvoyGatewayRemoteInfrastructureProviderServer interface {
	CreateOrUpdateProxyInfra(context.Context, *CreateOrUpdateProxyInfraRequest) (*CreateOrUpdateProxyInfraResponse, error)
	DeleteProxyInfra(context.Context, *DeleteProxyInfraRequest) (*DeleteProxyInfraResponse, error)
	CreateOrUpdateRateLimitInfra(context.Context, *CreateOrUpdateRateLimitInfraRequest) (*CreateOrUpdateRateLimitInfraResponse, error)
	DeleteRateLimitInfra(context.Context, *DeleteRateLimitInfraRequest) (*DeleteRateLimitInfraResponse, error)
	mustEmbedUnimplementedEnvoyGatewayRemoteInfrastructureProviderServer()
}

// UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer struct{}

func (UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer) CreateOrUpdateProxyInfra(context.Context, *CreateOrUpdateProxyInfraRequest) (*CreateOrUpdateProxyInfraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateProxyInfra not implemented")
}
func (UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer) DeleteProxyInfra(context.Context, *DeleteProxyInfraRequest) (*DeleteProxyInfraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProxyInfra not implemented")
}
func (UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer) CreateOrUpdateRateLimitInfra(context.Context, *CreateOrUpdateRateLimitInfraRequest) (*CreateOrUpdateRateLimitInfraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateRateLimitInfra not implemented")
}
func (UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer) DeleteRateLimitInfra(context.Context, *DeleteRateLimitInfraRequest) (*DeleteRateLimitInfraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRateLimitInfra not implemented")
}
func (UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer) mustEmbedUnimplementedEnvoyGatewayRemoteInfrastructureProviderServer() {
}
func (UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer) testEmbeddedByValue() {}

// UnsafeEnvoyGatewayRemoteInfrastructureProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvoyGatewayRemoteInfrastructureProviderServer will
// result in compilation errors.
type UnsafeEnvoyGatewayRemoteInfrastructureProviderServer interface {
	mustEmbedUnimplementedEnvoyGatewayRemoteInfrastructureProviderServer()
}

func RegisterEnvoyGatewayRemoteInfrastructureProviderServer(s grpc.ServiceRegistrar, srv EnvoyGatewayRemoteInfrastructureProviderServer) {
	// If the following call pancis, it indicates UnimplementedEnvoyGatewayRemoteInfrastructureProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnvoyGatewayRemoteInfrastructureProvider_ServiceDesc, srv)
}

func _EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateProxyInfra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateProxyInfraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).CreateOrUpdateProxyInfra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateProxyInfra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).CreateOrUpdateProxyInfra(ctx, req.(*CreateOrUpdateProxyInfraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyGatewayRemoteInfrastructureProvider_DeleteProxyInfra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProxyInfraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).DeleteProxyInfra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayRemoteInfrastructureProvider_DeleteProxyInfra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).DeleteProxyInfra(ctx, req.(*DeleteProxyInfraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateRateLimitInfra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateRateLimitInfraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).CreateOrUpdateRateLimitInfra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateRateLimitInfra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).CreateOrUpdateRateLimitInfra(ctx, req.(*CreateOrUpdateRateLimitInfraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyGatewayRemoteInfrastructureProvider_DeleteRateLimitInfra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRateLimitInfraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).DeleteRateLimitInfra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayRemoteInfrastructureProvider_DeleteRateLimitInfra_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayRemoteInfrastructureProviderServer).DeleteRateLimitInfra(ctx, req.(*DeleteRateLimitInfraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvoyGatewayRemoteInfrastructureProvider_ServiceDesc is the grpc.ServiceDesc for EnvoyGatewayRemoteInfrastructureProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvoyGatewayRemoteInfrastructureProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "envoygateway.remoteinfra.EnvoyGatewayRemoteInfrastructureProvider",
	HandlerType: (*EnvoyGatewayRemoteInfrastructureProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdateProxyInfra",
			Handler:    _EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateProxyInfra_Handler,
		},
		{
			MethodName: "DeleteProxyInfra",
			Handler:    _EnvoyGatewayRemoteInfrastructureProvider_DeleteProxyInfra_Handler,
		},
		{
			MethodName: "CreateOrUpdateRateLimitInfra",
			Handler:    _EnvoyGatewayRemoteInfrastructureProvider_CreateOrUpdateRateLimitInfra_Handler,
		},
		{
			MethodName: "DeleteRateLimitInfra",
			Handler:    _EnvoyGatewayRemoteInfrastructureProvider_DeleteRateLimitInfra_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/remoteinfra/service.proto",
}
