##@ Lint

.PHONY: lint
lint: ## Run all the linters
lint: go-fmt go-vet

.PHONY: go-fmt
go-fmt: ## Run go fmt on everything
	go fmt ./api/...
	go fmt ./internal/...
	go fmt ./cmd/...
	go fmt ./pkg/...

.PHONY: go-vet
go-vet: ## Run go vet on everything
	go vet ./api/...
	go vet ./internal/...
	go vet ./cmd/...
	go vet ./pkg/...
