// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BackendTrafficPolicyLister helps list BackendTrafficPolicies.
// All objects returned here must be treated as read-only.
type BackendTrafficPolicyLister interface {
	// List lists all BackendTrafficPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.BackendTrafficPolicy, err error)
	// BackendTrafficPolicies returns an object that can list and get BackendTrafficPolicies.
	BackendTrafficPolicies(namespace string) BackendTrafficPolicyNamespaceLister
	BackendTrafficPolicyListerExpansion
}

// backendTrafficPolicyLister implements the BackendTrafficPolicyLister interface.
type backendTrafficPolicyLister struct {
	listers.ResourceIndexer[*apiv1alpha1.BackendTrafficPolicy]
}

// NewBackendTrafficPolicyLister returns a new BackendTrafficPolicyLister.
func NewBackendTrafficPolicyLister(indexer cache.Indexer) BackendTrafficPolicyLister {
	return &backendTrafficPolicyLister{listers.New[*apiv1alpha1.BackendTrafficPolicy](indexer, apiv1alpha1.Resource("backendtrafficpolicy"))}
}

// BackendTrafficPolicies returns an object that can list and get BackendTrafficPolicies.
func (s *backendTrafficPolicyLister) BackendTrafficPolicies(namespace string) BackendTrafficPolicyNamespaceLister {
	return backendTrafficPolicyNamespaceLister{listers.NewNamespaced[*apiv1alpha1.BackendTrafficPolicy](s.ResourceIndexer, namespace)}
}

// BackendTrafficPolicyNamespaceLister helps list and get BackendTrafficPolicies.
// All objects returned here must be treated as read-only.
type BackendTrafficPolicyNamespaceLister interface {
	// List lists all BackendTrafficPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.BackendTrafficPolicy, err error)
	// Get retrieves the BackendTrafficPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.BackendTrafficPolicy, error)
	BackendTrafficPolicyNamespaceListerExpansion
}

// backendTrafficPolicyNamespaceLister implements the BackendTrafficPolicyNamespaceLister
// interface.
type backendTrafficPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.BackendTrafficPolicy]
}
