// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SecurityPolicyLister helps list SecurityPolicies.
// All objects returned here must be treated as read-only.
type SecurityPolicyLister interface {
	// List lists all SecurityPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.SecurityPolicy, err error)
	// SecurityPolicies returns an object that can list and get SecurityPolicies.
	SecurityPolicies(namespace string) SecurityPolicyNamespaceLister
	SecurityPolicyListerExpansion
}

// securityPolicyLister implements the SecurityPolicyLister interface.
type securityPolicyLister struct {
	listers.ResourceIndexer[*apiv1alpha1.SecurityPolicy]
}

// NewSecurityPolicyLister returns a new SecurityPolicyLister.
func NewSecurityPolicyLister(indexer cache.Indexer) SecurityPolicyLister {
	return &securityPolicyLister{listers.New[*apiv1alpha1.SecurityPolicy](indexer, apiv1alpha1.Resource("securitypolicy"))}
}

// SecurityPolicies returns an object that can list and get SecurityPolicies.
func (s *securityPolicyLister) SecurityPolicies(namespace string) SecurityPolicyNamespaceLister {
	return securityPolicyNamespaceLister{listers.NewNamespaced[*apiv1alpha1.SecurityPolicy](s.ResourceIndexer, namespace)}
}

// SecurityPolicyNamespaceLister helps list and get SecurityPolicies.
// All objects returned here must be treated as read-only.
type SecurityPolicyNamespaceLister interface {
	// List lists all SecurityPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.SecurityPolicy, err error)
	// Get retrieves the SecurityPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.SecurityPolicy, error)
	SecurityPolicyNamespaceListerExpansion
}

// securityPolicyNamespaceLister implements the SecurityPolicyNamespaceLister
// interface.
type securityPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.SecurityPolicy]
}
