// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClientTrafficPolicyLister helps list ClientTrafficPolicies.
// All objects returned here must be treated as read-only.
type ClientTrafficPolicyLister interface {
	// List lists all ClientTrafficPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ClientTrafficPolicy, err error)
	// ClientTrafficPolicies returns an object that can list and get ClientTrafficPolicies.
	ClientTrafficPolicies(namespace string) ClientTrafficPolicyNamespaceLister
	ClientTrafficPolicyListerExpansion
}

// clientTrafficPolicyLister implements the ClientTrafficPolicyLister interface.
type clientTrafficPolicyLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ClientTrafficPolicy]
}

// NewClientTrafficPolicyLister returns a new ClientTrafficPolicyLister.
func NewClientTrafficPolicyLister(indexer cache.Indexer) ClientTrafficPolicyLister {
	return &clientTrafficPolicyLister{listers.New[*apiv1alpha1.ClientTrafficPolicy](indexer, apiv1alpha1.Resource("clienttrafficpolicy"))}
}

// ClientTrafficPolicies returns an object that can list and get ClientTrafficPolicies.
func (s *clientTrafficPolicyLister) ClientTrafficPolicies(namespace string) ClientTrafficPolicyNamespaceLister {
	return clientTrafficPolicyNamespaceLister{listers.NewNamespaced[*apiv1alpha1.ClientTrafficPolicy](s.ResourceIndexer, namespace)}
}

// ClientTrafficPolicyNamespaceLister helps list and get ClientTrafficPolicies.
// All objects returned here must be treated as read-only.
type ClientTrafficPolicyNamespaceLister interface {
	// List lists all ClientTrafficPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ClientTrafficPolicy, err error)
	// Get retrieves the ClientTrafficPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.ClientTrafficPolicy, error)
	ClientTrafficPolicyNamespaceListerExpansion
}

// clientTrafficPolicyNamespaceLister implements the ClientTrafficPolicyNamespaceLister
// interface.
type clientTrafficPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ClientTrafficPolicy]
}
