// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EnvoyProxyLister helps list EnvoyProxies.
// All objects returned here must be treated as read-only.
type EnvoyProxyLister interface {
	// List lists all EnvoyProxies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.EnvoyProxy, err error)
	// EnvoyProxies returns an object that can list and get EnvoyProxies.
	EnvoyProxies(namespace string) EnvoyProxyNamespaceLister
	EnvoyProxyListerExpansion
}

// envoyProxyLister implements the EnvoyProxyLister interface.
type envoyProxyLister struct {
	listers.ResourceIndexer[*apiv1alpha1.EnvoyProxy]
}

// NewEnvoyProxyLister returns a new EnvoyProxyLister.
func NewEnvoyProxyLister(indexer cache.Indexer) EnvoyProxyLister {
	return &envoyProxyLister{listers.New[*apiv1alpha1.EnvoyProxy](indexer, apiv1alpha1.Resource("envoyproxy"))}
}

// EnvoyProxies returns an object that can list and get EnvoyProxies.
func (s *envoyProxyLister) EnvoyProxies(namespace string) EnvoyProxyNamespaceLister {
	return envoyProxyNamespaceLister{listers.NewNamespaced[*apiv1alpha1.EnvoyProxy](s.ResourceIndexer, namespace)}
}

// EnvoyProxyNamespaceLister helps list and get EnvoyProxies.
// All objects returned here must be treated as read-only.
type EnvoyProxyNamespaceLister interface {
	// List lists all EnvoyProxies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.EnvoyProxy, err error)
	// Get retrieves the EnvoyProxy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.EnvoyProxy, error)
	EnvoyProxyNamespaceListerExpansion
}

// envoyProxyNamespaceLister implements the EnvoyProxyNamespaceLister
// interface.
type envoyProxyNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.EnvoyProxy]
}
