// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BackendListerExpansion allows custom methods to be added to
// BackendLister.
type BackendListerExpansion interface{}

// BackendNamespaceListerExpansion allows custom methods to be added to
// BackendNamespaceLister.
type BackendNamespaceListerExpansion interface{}

// BackendTrafficPolicyListerExpansion allows custom methods to be added to
// BackendTrafficPolicyLister.
type BackendTrafficPolicyListerExpansion interface{}

// BackendTrafficPolicyNamespaceListerExpansion allows custom methods to be added to
// BackendTrafficPolicyNamespaceLister.
type BackendTrafficPolicyNamespaceListerExpansion interface{}

// ClientTrafficPolicyListerExpansion allows custom methods to be added to
// ClientTrafficPolicyLister.
type ClientTrafficPolicyListerExpansion interface{}

// ClientTrafficPolicyNamespaceListerExpansion allows custom methods to be added to
// ClientTrafficPolicyNamespaceLister.
type ClientTrafficPolicyNamespaceListerExpansion interface{}

// EnvoyExtensionPolicyListerExpansion allows custom methods to be added to
// EnvoyExtensionPolicyLister.
type EnvoyExtensionPolicyListerExpansion interface{}

// EnvoyExtensionPolicyNamespaceListerExpansion allows custom methods to be added to
// EnvoyExtensionPolicyNamespaceLister.
type EnvoyExtensionPolicyNamespaceListerExpansion interface{}

// EnvoyPatchPolicyListerExpansion allows custom methods to be added to
// EnvoyPatchPolicyLister.
type EnvoyPatchPolicyListerExpansion interface{}

// EnvoyPatchPolicyNamespaceListerExpansion allows custom methods to be added to
// EnvoyPatchPolicyNamespaceLister.
type EnvoyPatchPolicyNamespaceListerExpansion interface{}

// EnvoyProxyListerExpansion allows custom methods to be added to
// EnvoyProxyLister.
type EnvoyProxyListerExpansion interface{}

// EnvoyProxyNamespaceListerExpansion allows custom methods to be added to
// EnvoyProxyNamespaceLister.
type EnvoyProxyNamespaceListerExpansion interface{}

// HTTPRouteFilterListerExpansion allows custom methods to be added to
// HTTPRouteFilterLister.
type HTTPRouteFilterListerExpansion interface{}

// HTTPRouteFilterNamespaceListerExpansion allows custom methods to be added to
// HTTPRouteFilterNamespaceLister.
type HTTPRouteFilterNamespaceListerExpansion interface{}

// SecurityPolicyListerExpansion allows custom methods to be added to
// SecurityPolicyLister.
type SecurityPolicyListerExpansion interface{}

// SecurityPolicyNamespaceListerExpansion allows custom methods to be added to
// SecurityPolicyNamespaceLister.
type SecurityPolicyNamespaceListerExpansion interface{}
