// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/gateway/pkg/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSecurityPolicies implements SecurityPolicyInterface
type fakeSecurityPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.SecurityPolicy, *v1alpha1.SecurityPolicyList]
	Fake *FakeEnvoyGatewayV1alpha1
}

func newFakeSecurityPolicies(fake *FakeEnvoyGatewayV1alpha1, namespace string) apiv1alpha1.SecurityPolicyInterface {
	return &fakeSecurityPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.SecurityPolicy, *v1alpha1.SecurityPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("securitypolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("SecurityPolicy"),
			func() *v1alpha1.SecurityPolicy { return &v1alpha1.SecurityPolicy{} },
			func() *v1alpha1.SecurityPolicyList { return &v1alpha1.SecurityPolicyList{} },
			func(dst, src *v1alpha1.SecurityPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SecurityPolicyList) []*v1alpha1.SecurityPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SecurityPolicyList, items []*v1alpha1.SecurityPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
