// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/gateway/pkg/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeEnvoyPatchPolicies implements EnvoyPatchPolicyInterface
type fakeEnvoyPatchPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.EnvoyPatchPolicy, *v1alpha1.EnvoyPatchPolicyList]
	Fake *FakeEnvoyGatewayV1alpha1
}

func newFakeEnvoyPatchPolicies(fake *FakeEnvoyGatewayV1alpha1, namespace string) apiv1alpha1.EnvoyPatchPolicyInterface {
	return &fakeEnvoyPatchPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.EnvoyPatchPolicy, *v1alpha1.EnvoyPatchPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("envoypatchpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("EnvoyPatchPolicy"),
			func() *v1alpha1.EnvoyPatchPolicy { return &v1alpha1.EnvoyPatchPolicy{} },
			func() *v1alpha1.EnvoyPatchPolicyList { return &v1alpha1.EnvoyPatchPolicyList{} },
			func(dst, src *v1alpha1.EnvoyPatchPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.EnvoyPatchPolicyList) []*v1alpha1.EnvoyPatchPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.EnvoyPatchPolicyList, items []*v1alpha1.EnvoyPatchPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
