// Copyright Envoy Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: envoygateway/extension/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnvoyGatewayExtensionService_PostRouteModify_FullMethodName        = "/envoygateway.extension.v1.EnvoyGatewayExtensionService/PostRouteModify"
	EnvoyGatewayExtensionService_PostVirtualHostModify_FullMethodName  = "/envoygateway.extension.v1.EnvoyGatewayExtensionService/PostVirtualHostModify"
	EnvoyGatewayExtensionService_PostHTTPListenerModify_FullMethodName = "/envoygateway.extension.v1.EnvoyGatewayExtensionService/PostHTTPListenerModify"
	EnvoyGatewayExtensionService_PostClusterModify_FullMethodName      = "/envoygateway.extension.v1.EnvoyGatewayExtensionService/PostClusterModify"
	EnvoyGatewayExtensionService_PostTranslateModify_FullMethodName    = "/envoygateway.extension.v1.EnvoyGatewayExtensionService/PostTranslateModify"
)

// EnvoyGatewayExtensionServiceClient is the client API for EnvoyGatewayExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnvoyGatewayExtensionServiceClient interface {
	// PostRouteModify provides a way for extensions to modify a route generated by Envoy Gateway before it is finalized.
	// Doing so allows extensions to configure/modify route fields configured by Envoy Gateway and also to configure the
	// Route's TypedPerFilterConfig which may be desirable to do things such as pass settings and information to
	// ext_authz filters.
	// PostRouteModify also passes a list of Unstructured data for the externalRefs owned by the extension on the HTTPRoute that
	// created this xDS route
	// PostRouteModify will only be executed if an extension is loaded and only on Routes which were generated from an HTTPRoute
	// that uses extension resources as externalRef filters.
	PostRouteModify(ctx context.Context, in *PostRouteModifyRequest, opts ...grpc.CallOption) (*PostRouteModifyResponse, error)
	// PostVirtualHostModify provides a way for extensions to modify a VirtualHost generated by Envoy Gateway before it is finalized.
	// An extension can also make use of this hook to generate and insert entirely new Routes not generated by Envoy Gateway.
	// PostVirtualHostModify is always executed when an extension is loaded. An extension may return nil to not make any changes
	// to it.
	PostVirtualHostModify(ctx context.Context, in *PostVirtualHostModifyRequest, opts ...grpc.CallOption) (*PostVirtualHostModifyResponse, error)
	// PostHTTPListenerModify allows an extension to make changes to a Listener generated by Envoy Gateway before it is finalized.
	// PostHTTPListenerModify is always executed when an extension is loaded. An extension may return nil
	// in order to not make any changes to it.
	PostHTTPListenerModify(ctx context.Context, in *PostHTTPListenerModifyRequest, opts ...grpc.CallOption) (*PostHTTPListenerModifyResponse, error)
	// PostClusterModify provides a way for extensions to modify clusters generated by Envoy Gateway for custom backends.
	// This allows extensions to modify cluster configurations for custom backend types while letting Envoy Gateway
	// control cluster naming and basic configuration. This hook is called when custom backend resources are used
	// in HTTPRoute or GRPCRoute backendRefs.
	PostClusterModify(ctx context.Context, in *PostClusterModifyRequest, opts ...grpc.CallOption) (*PostClusterModifyResponse, error)
	// PostTranslateModify allows an extension to modify the clusters and secrets in the xDS config.
	// This allows for inserting clusters that may change along with extension specific configuration to be dynamically created rather than
	// using custom bootstrap config which would be sufficient for clusters that are static and not prone to have their configurations changed.
	// An example of how this may be used is to inject a cluster that will be used by an ext_authz http filter created by the extension.
	// The list of clusters and secrets returned by the extension are used as the final list of all clusters and secrets
	// PostTranslateModify is always executed when an extension is loaded
	PostTranslateModify(ctx context.Context, in *PostTranslateModifyRequest, opts ...grpc.CallOption) (*PostTranslateModifyResponse, error)
}

type envoyGatewayExtensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvoyGatewayExtensionServiceClient(cc grpc.ClientConnInterface) EnvoyGatewayExtensionServiceClient {
	return &envoyGatewayExtensionServiceClient{cc}
}

func (c *envoyGatewayExtensionServiceClient) PostRouteModify(ctx context.Context, in *PostRouteModifyRequest, opts ...grpc.CallOption) (*PostRouteModifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostRouteModifyResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayExtensionService_PostRouteModify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyGatewayExtensionServiceClient) PostVirtualHostModify(ctx context.Context, in *PostVirtualHostModifyRequest, opts ...grpc.CallOption) (*PostVirtualHostModifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostVirtualHostModifyResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayExtensionService_PostVirtualHostModify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyGatewayExtensionServiceClient) PostHTTPListenerModify(ctx context.Context, in *PostHTTPListenerModifyRequest, opts ...grpc.CallOption) (*PostHTTPListenerModifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostHTTPListenerModifyResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayExtensionService_PostHTTPListenerModify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyGatewayExtensionServiceClient) PostClusterModify(ctx context.Context, in *PostClusterModifyRequest, opts ...grpc.CallOption) (*PostClusterModifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostClusterModifyResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayExtensionService_PostClusterModify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envoyGatewayExtensionServiceClient) PostTranslateModify(ctx context.Context, in *PostTranslateModifyRequest, opts ...grpc.CallOption) (*PostTranslateModifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostTranslateModifyResponse)
	err := c.cc.Invoke(ctx, EnvoyGatewayExtensionService_PostTranslateModify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvoyGatewayExtensionServiceServer is the server API for EnvoyGatewayExtensionService service.
// All implementations must embed UnimplementedEnvoyGatewayExtensionServiceServer
// for forward compatibility.
type EnvoyGatewayExtensionServiceServer interface {
	// PostRouteModify provides a way for extensions to modify a route generated by Envoy Gateway before it is finalized.
	// Doing so allows extensions to configure/modify route fields configured by Envoy Gateway and also to configure the
	// Route's TypedPerFilterConfig which may be desirable to do things such as pass settings and information to
	// ext_authz filters.
	// PostRouteModify also passes a list of Unstructured data for the externalRefs owned by the extension on the HTTPRoute that
	// created this xDS route
	// PostRouteModify will only be executed if an extension is loaded and only on Routes which were generated from an HTTPRoute
	// that uses extension resources as externalRef filters.
	PostRouteModify(context.Context, *PostRouteModifyRequest) (*PostRouteModifyResponse, error)
	// PostVirtualHostModify provides a way for extensions to modify a VirtualHost generated by Envoy Gateway before it is finalized.
	// An extension can also make use of this hook to generate and insert entirely new Routes not generated by Envoy Gateway.
	// PostVirtualHostModify is always executed when an extension is loaded. An extension may return nil to not make any changes
	// to it.
	PostVirtualHostModify(context.Context, *PostVirtualHostModifyRequest) (*PostVirtualHostModifyResponse, error)
	// PostHTTPListenerModify allows an extension to make changes to a Listener generated by Envoy Gateway before it is finalized.
	// PostHTTPListenerModify is always executed when an extension is loaded. An extension may return nil
	// in order to not make any changes to it.
	PostHTTPListenerModify(context.Context, *PostHTTPListenerModifyRequest) (*PostHTTPListenerModifyResponse, error)
	// PostClusterModify provides a way for extensions to modify clusters generated by Envoy Gateway for custom backends.
	// This allows extensions to modify cluster configurations for custom backend types while letting Envoy Gateway
	// control cluster naming and basic configuration. This hook is called when custom backend resources are used
	// in HTTPRoute or GRPCRoute backendRefs.
	PostClusterModify(context.Context, *PostClusterModifyRequest) (*PostClusterModifyResponse, error)
	// PostTranslateModify allows an extension to modify the clusters and secrets in the xDS config.
	// This allows for inserting clusters that may change along with extension specific configuration to be dynamically created rather than
	// using custom bootstrap config which would be sufficient for clusters that are static and not prone to have their configurations changed.
	// An example of how this may be used is to inject a cluster that will be used by an ext_authz http filter created by the extension.
	// The list of clusters and secrets returned by the extension are used as the final list of all clusters and secrets
	// PostTranslateModify is always executed when an extension is loaded
	PostTranslateModify(context.Context, *PostTranslateModifyRequest) (*PostTranslateModifyResponse, error)
	mustEmbedUnimplementedEnvoyGatewayExtensionServiceServer()
}

// UnimplementedEnvoyGatewayExtensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnvoyGatewayExtensionServiceServer struct{}

func (UnimplementedEnvoyGatewayExtensionServiceServer) PostRouteModify(context.Context, *PostRouteModifyRequest) (*PostRouteModifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostRouteModify not implemented")
}
func (UnimplementedEnvoyGatewayExtensionServiceServer) PostVirtualHostModify(context.Context, *PostVirtualHostModifyRequest) (*PostVirtualHostModifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostVirtualHostModify not implemented")
}
func (UnimplementedEnvoyGatewayExtensionServiceServer) PostHTTPListenerModify(context.Context, *PostHTTPListenerModifyRequest) (*PostHTTPListenerModifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostHTTPListenerModify not implemented")
}
func (UnimplementedEnvoyGatewayExtensionServiceServer) PostClusterModify(context.Context, *PostClusterModifyRequest) (*PostClusterModifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostClusterModify not implemented")
}
func (UnimplementedEnvoyGatewayExtensionServiceServer) PostTranslateModify(context.Context, *PostTranslateModifyRequest) (*PostTranslateModifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTranslateModify not implemented")
}
func (UnimplementedEnvoyGatewayExtensionServiceServer) mustEmbedUnimplementedEnvoyGatewayExtensionServiceServer() {
}
func (UnimplementedEnvoyGatewayExtensionServiceServer) testEmbeddedByValue() {}

// UnsafeEnvoyGatewayExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvoyGatewayExtensionServiceServer will
// result in compilation errors.
type UnsafeEnvoyGatewayExtensionServiceServer interface {
	mustEmbedUnimplementedEnvoyGatewayExtensionServiceServer()
}

func RegisterEnvoyGatewayExtensionServiceServer(s grpc.ServiceRegistrar, srv EnvoyGatewayExtensionServiceServer) {
	// If the following call pancis, it indicates UnimplementedEnvoyGatewayExtensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnvoyGatewayExtensionService_ServiceDesc, srv)
}

func _EnvoyGatewayExtensionService_PostRouteModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRouteModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayExtensionServiceServer).PostRouteModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayExtensionService_PostRouteModify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayExtensionServiceServer).PostRouteModify(ctx, req.(*PostRouteModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyGatewayExtensionService_PostVirtualHostModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostVirtualHostModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayExtensionServiceServer).PostVirtualHostModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayExtensionService_PostVirtualHostModify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayExtensionServiceServer).PostVirtualHostModify(ctx, req.(*PostVirtualHostModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyGatewayExtensionService_PostHTTPListenerModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostHTTPListenerModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayExtensionServiceServer).PostHTTPListenerModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayExtensionService_PostHTTPListenerModify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayExtensionServiceServer).PostHTTPListenerModify(ctx, req.(*PostHTTPListenerModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyGatewayExtensionService_PostClusterModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostClusterModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayExtensionServiceServer).PostClusterModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayExtensionService_PostClusterModify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayExtensionServiceServer).PostClusterModify(ctx, req.(*PostClusterModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvoyGatewayExtensionService_PostTranslateModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTranslateModifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvoyGatewayExtensionServiceServer).PostTranslateModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnvoyGatewayExtensionService_PostTranslateModify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvoyGatewayExtensionServiceServer).PostTranslateModify(ctx, req.(*PostTranslateModifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvoyGatewayExtensionService_ServiceDesc is the grpc.ServiceDesc for EnvoyGatewayExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvoyGatewayExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "envoygateway.extension.v1.EnvoyGatewayExtensionService",
	HandlerType: (*EnvoyGatewayExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostRouteModify",
			Handler:    _EnvoyGatewayExtensionService_PostRouteModify_Handler,
		},
		{
			MethodName: "PostVirtualHostModify",
			Handler:    _EnvoyGatewayExtensionService_PostVirtualHostModify_Handler,
		},
		{
			MethodName: "PostHTTPListenerModify",
			Handler:    _EnvoyGatewayExtensionService_PostHTTPListenerModify_Handler,
		},
		{
			MethodName: "PostClusterModify",
			Handler:    _EnvoyGatewayExtensionService_PostClusterModify_Handler,
		},
		{
			MethodName: "PostTranslateModify",
			Handler:    _EnvoyGatewayExtensionService_PostTranslateModify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "envoygateway/extension/v1/service.proto",
}
