name: Issue and PR comment commands

permissions: {}

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: jpmcb/prow-github-actions@187c5e3cd95a329c43448e1bdb3b1f5249232e44  # v3.0.1
        with:
          prow-commands: '/assign
            /unassign
            /area
            /kind
            /priority
            /remove
            /close
            /reopen
            /lock
            /milestone
            /hold
            /cc
            /uncc'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
